services:
  whatsapp:
    image: ghcr.io/rodagency10/go-whatsapp-web-multidevice:dev
    restart: always
    ports:
      - "${WA_PORT:-3080}:3080"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --basic-auth=${WA_USER}:${WA_PASSWORD}
      - --port=${WA_PORT:-3080}
      - --debug=false
      - --os=Chrome
      - --account-validation=false
      - --auto-mark-read=true
    environment:
      - WA_USER=${WA_USER:-admin}
      - WA_PASSWORD=${WA_PASSWORD:-changeme}


volumes:
  whatsapp:
